apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-test-app
  namespace: ocm-system
  provider:
    name: acme.org
  version: v1.0.0
repositoryContexts: []
spec: 
  interval: 10m0s
  repository:  
    url: ghcr.io/mohammad-ammar14
    secretRef: 
      name: creds    
  references:
  - componentName: github.com/acme/ocm-test-app
    name: ocm-test-app
    version: v1.0.0
  - componentName: github.com/acme/ocm-frontend-app
    name: ocm-frontend-app
    version: v1.0.0

# apiVersion: delivery.ocm.software/v1alpha1
# kind: ComponentVersion
# metadata:
#   name: podinfo
#   namespace: ocm-system
# spec:
#   interval: 10m0s
#   component: github.com/acme/podify
#   version:
#     semver: v1.0.0
#   repository:
#     url: ghcr.io/mohammad-ammar14
#     secretRef:
#       name: creds
#   references: 
#     expand: true  
#   verify:
#   - name: alice
#     publicKey:
#       secretRef:
#         name: alice-publickey    
